version: '3'

services:
  djangotask_server:
    build: .
    container_name: server
    working_dir: /var/www/djangotask
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - ./:/var/www/djangotask
    command: python manage.py runserver 0.0.0.0:$SERVER_PORT
    environment:
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
      - PGHOST=$DATABASE_HOST
    env_file:
      - .env
    depends_on:
      - djangotask_database
  djangotask_database:
    container_name: database
    image: postgres:latest
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql