# Generated by Django 2.2 on 2019-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='blogger',
            name='hobbies',
            field=models.ManyToManyField(to='accounts.Hobby'),
        ),
        migrations.AddField(
            model_name='reader',
            name='hobbies',
            field=models.ManyToManyField(to='accounts.Interest'),
        ),
    ]
