# Generated by Django 2.2 on 2019-07-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_auto_20190726_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='creator',
            new_name='starter',
        ),
    ]
