# Generated by Django 2.2 on 2019-08-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveIntegerField(choices=[(1, 'created'), (2, 'updated'), (3, 'deleted')])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_board', to='boards.Board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
