# Generated by Django 2.2 on 2019-08-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='board',
        ),
        migrations.AddField(
            model_name='logs',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_topic', to='boards.Topic'),
        ),
    ]
