# Generated by Django 2.2 on 2019-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190808_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='kind',
            field=models.PositiveIntegerField(choices=[(0, 'created'), (1, 'updated'), (2, 'deleted')]),
        ),
    ]
