# Generated by Django 2.2 on 2019-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(to='boards.Photo'),
        ),
    ]
