# Generated by Django 2.2 on 2019-08-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_post_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='boards.Post'),
        ),
    ]
