# Generated by Django 2.2 on 2019-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20190816_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='non_active',
            field=models.BooleanField(default=False),
        ),
    ]
